### ISSUE TITLE
Update to latest completion model

### ISSUE THREAD

**Issue by Industry** [k1w33d/AITypo#1]
This is wonderful. Would you mind updating it to the latest versions of OpenAI's completion models. Some of the code needs a little fixing.

Is there a better way to have this run-on the fly in other text fields instead of having to jump back and forth from the GUI and whatever I'm doing?

**Comment by k1w33d** [comment]
I have updated the completion model to use GPT-3.5-Turbo-Instruct and it works without errors. The goal is to have this run similar to how autocorrect works on phones, where everything is processed within the text box you are actually wanting to use. I will keep pecking at this until I get it to do what I want or someone else does it.

`ENGINE_NAME = 'gpt-3.5-turbo-instruct'`

**Comment by Industry** [comment]
Don't believe that fixed it. This is the error that I receive. Why not upgrade to a non-deprecated version of the model so it's future proof.

> You tried to access openai.Completion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.
> 
> You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.
> 
> Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`
> 
> A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

**Comment by k1w33d** [comment]
Thank you for that. I hadn't updated the OpenAI install locally so was not getting the error you mentioned. Uograded the install and saw the error and have now at least stopped it from showing. I need to go through and clean everything up.
